# Render deployment configuration
# This file tells Render how to build and run your app

version: "1"
services:
  - type: web
    name: attendsys
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
      - key: MONGODB_URI
        fromDatabase: AttendSys-MongoDB
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      - key: MAX_FILE_SIZE
        value: 5000000

databases:
  - name: AttendSys-MongoDB
    plan: free
